### ISSUE TITLE
亲爱的作者，TypeScript error

### ISSUE THREAD

**Issue by felix-cao** [0xLLLLH/react-krpano-examples#1]
亲爱的博主，跑不起来
![image](https://user-images.githubusercontent.com/8563874/106227197-c0071880-6223-11eb-9002-c8feb03391af.png)

**Comment by 0xLLLLH** [comment]
应该是忘记更新这个仓库依赖的版本了，我本地开发用了npm link所以当时检查的时候没发现。
只需要将`@0xlllh/react-krpano`升级到最新版本即可修复问题。
